---
title: "Linear Model with R: Chapter 5"
author: Han Chenyue
editor: source
format:
  html:
    code-fold: true
    code-summary: "Show the code"
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  # echo = FALSE,
  digits = 4,
  scipen = 2
)
```

# Chapter 5

## Exercises

### Q1

#### q1a

```{r}
data(prostate, package = "faraway")
lm_q1a <- lm(lpsa ~ ., data = prostate)
summary(lm_q1a)
```

```{r}
new_patient = data.frame(
  lcavol = 1.44692,
  lweight = 3.62301,
  age = 65.00000,
  lbph = 0.30010,
  svi = 0.00000,
  lcp = -0.79851,
  gleason = 7.00000,
  pgg45 = 15.00000
)
predict(lm_q1a, newdata = new_patient, interval = "prediction")
```

```{r}
# Sanity check: Manual calculations
# Extract coefficients
coefficient_vector_of_lm_q1a <- coef(lm_q1a)
coefficient_vector_of_lm_q1a

new_patient_manual_calculations <- data.frame(
  lcavol = 1.44692,
  lweight = 3.62301,
  age = 65,
  lbph = 0.3001,
  svi = 0,
  lcp = -0.79851,
  gleason = 7,
  pgg45 = 15
)
new_patient_manual_calculations

# Add intercept column to new data
new_patient_manual_calculations$`(Intercept)` <- 1
new_patient_manual_calculations

# Reorder columns to match coefficients' order
new_patient_manual_calculations <- new_patient_manual_calculations[names(
  coefficient_vector_of_lm_q1a
)]
new_patient_manual_calculations

# Multiply and summation
manual_prediction <- as.numeric(
  as.matrix(new_patient_manual_calculations) %*% coefficient_vector_of_lm_q1a
)
manual_prediction
near(
  manual_prediction,
  predict(lm_q1a, newdata = new_patient, interval = "prediction")[1, "fit"]
)
```

To compute the CI manually, we will need:

$$
\hat{y}_0 \pm t^{(\alpha / 2)}_{n-p} \hat{\sigma} \sqrt{1 + x_0^T (X^T X)^{-1} x_0}
$$

$$
\hat{\sigma} = \sqrt{\frac{RSS}{n - p}} = \sqrt{\frac{\hat{e}^T \hat{e}}{n - p}} = \sqrt{\frac{\sum_{i=1}^n \hat{e}_i^2}{n - p}}
$$

```{r}
y <- prostate$lpsa
y

X <- model.matrix(lm_q1a)
X


new_patient_manual_calculations <- data.frame(
  intercept = 1,
  lcavol = 1.44692,
  lweight = 3.62301,
  age = 65,
  lbph = 0.3001,
  svi = 0,
  lcp = -0.79851,
  gleason = 7,
  pgg45 = 15
)

new_patient_manual_calculations

beta_hat <- solve(t(X) %*% X) %*% t(X) %*% y
x0 <- t(as.matrix(new_patient_manual_calculations))
epsilon <- y - X %*% beta_hat
rss <- t(epsilon) %*% epsilon
n <- nrow(X)
p <- ncol(X)
sigma_hat <- sqrt(rss / (n - p))
```

```{r}
y0 <- t(x0) %*% beta_hat
near(y0, manual_prediction)
near(
  y0,
  predict(lm_q1a, newdata = new_patient, interval = "prediction")[1, "fit"]
)
```

```{r}
t_critical <- qt(0.975, df = n - p)
t_critical

lwr <- y0 -
  t_critical * sigma_hat * sqrt(1 + t(x0) %*% solve(t(X) %*% X) %*% x0)
lwr
near(
  lwr,
  predict(lm_q1a, newdata = new_patient, interval = "prediction")[1, "lwr"]
)

upr <- y0 +
  t_critical * sigma_hat * sqrt(1 + t(x0) %*% solve(t(X) %*% X) %*% x0)
upr
near(
  upr,
  predict(lm_q1a, newdata = new_patient, interval = "prediction")[1, "upr"]
)
```

#### q1b

```{r}

```