<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Han Chenyue">

<title>Linear_Model_with_R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="chapter2_files/libs/clipboard/clipboard.min.js"></script>
<script src="chapter2_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="chapter2_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="chapter2_files/libs/quarto-html/popper.min.js"></script>
<script src="chapter2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="chapter2_files/libs/quarto-html/anchor.min.js"></script>
<link href="chapter2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="chapter2_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="chapter2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="chapter2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="chapter2_files/libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#chapter-2" id="toc-chapter-2" class="nav-link active" data-scroll-target="#chapter-2">Chapter 2</a>
  <ul class="collapse">
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a>
  <ul class="collapse">
  <li><a href="#q1" id="toc-q1" class="nav-link" data-scroll-target="#q1">Q1</a></li>
  <li><a href="#q2" id="toc-q2" class="nav-link" data-scroll-target="#q2">Q2</a></li>
  <li><a href="#q3" id="toc-q3" class="nav-link" data-scroll-target="#q3">Q3</a></li>
  <li><a href="#q4" id="toc-q4" class="nav-link" data-scroll-target="#q4">Q4</a></li>
  <li><a href="#q5" id="toc-q5" class="nav-link" data-scroll-target="#q5">Q5</a></li>
  <li><a href="#q6" id="toc-q6" class="nav-link" data-scroll-target="#q6">Q6</a></li>
  <li><a href="#q7" id="toc-q7" class="nav-link" data-scroll-target="#q7">Q7</a></li>
  <li><a href="#q8" id="toc-q8" class="nav-link" data-scroll-target="#q8">Q8</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Linear_Model_with_R</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Han Chenyue </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="chapter-2" class="level1">
<h1>Chapter 2</h1>
<section id="exercises" class="level2">
<h2 class="anchored" data-anchor-id="exercises">Exercises</h2>
<section id="q1" class="level3">
<h3 class="anchored" data-anchor-id="q1">Q1</h3>
<section id="q1a" class="level4">
<h4 class="anchored" data-anchor-id="q1a">q1a</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(teengamb, <span class="at">package =</span> <span class="st">"faraway"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>lm_q1a <span class="ot">&lt;-</span> <span class="fu">lm</span>(gamble <span class="sc">~</span> sex <span class="sc">+</span> status <span class="sc">+</span> income <span class="sc">+</span> verbal, <span class="at">data =</span> teengamb)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_q1a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = gamble ~ sex + status + income + verbal, data = teengamb)

Residuals:
    Min      1Q  Median      3Q     Max 
-51.082 -11.320  -1.451   9.452  94.252 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  22.55565   17.19680   1.312   0.1968    
sex         -22.11833    8.21111  -2.694   0.0101 *  
status        0.05223    0.28111   0.186   0.8535    
income        4.96198    1.02539   4.839 1.79e-05 ***
verbal       -2.95949    2.17215  -1.362   0.1803    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 22.69 on 42 degrees of freedom
Multiple R-squared:  0.5267,    Adjusted R-squared:  0.4816 
F-statistic: 11.69 on 4 and 42 DF,  p-value: 1.815e-06</code></pre>
</div>
</div>
</section>
<section id="q1b" class="level4">
<h4 class="anchored" data-anchor-id="q1b">q1b</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">round</span>(<span class="fu">summary</span>(lm_q1a)<span class="sc">$</span>r.squared <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>), <span class="st">"%"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>52.67 %</code></pre>
</div>
</div>
<p><code>Multiple R-square: 52.67%</code></p>
</section>
<section id="q1c" class="level4">
<h4 class="anchored" data-anchor-id="q1c">q1c</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Index: "</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">which.max</span>(<span class="fu">residuals</span>(lm_q1a)),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"</span><span class="sc">\n</span><span class="st">Residual"</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">max</span>(<span class="fu">residuals</span>(lm_q1a))</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Index:  24 
Residual 94.25222</code></pre>
</div>
</div>
</section>
<section id="q1d" class="level4">
<h4 class="anchored" data-anchor-id="q1d">q1d</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Mean of residuals: "</span>,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">signif</span>(<span class="fu">mean</span>(<span class="fu">residuals</span>(lm_q1a)), <span class="dv">3</span>),</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"</span><span class="sc">\n</span><span class="st">Median of residuals: "</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">signif</span>(<span class="fu">median</span>(<span class="fu">residuals</span>(lm_q1a)), <span class="dv">3</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Mean of residuals:  -1.56e-16 
Median of residuals:  -1.45</code></pre>
</div>
</div>
<p>We expect the mean of the residuals from a linear model to be always zero (<em>assuming we do not drop the intercept term</em>, <span class="math inline">\(\beta_0\)</span>), <span class="math inline">\(\bar{\hat{\epsilon}} = 0\)</span>. Unlike the mean of the residuals, which is mathematically guaranteed to be zero in an OLS model, the median is not. Consequently, the median is often close to zero but rarely, if ever, exactly zero.</p>
</section>
<section id="q1e" class="level4">
<h4 class="anchored" data-anchor-id="q1e">q1e</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Correlation of the residuals with the fitted values: "</span>,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">signif</span>(<span class="fu">cor</span>(<span class="fu">residuals</span>(lm_q1a), <span class="fu">predict</span>(lm_q1a)), <span class="dv">3</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Correlation of the residuals with the fitted values:  4.76e-17</code></pre>
</div>
</div>
<p>The correlation is effectively zero because the residual vector <span class="math inline">\(\hat{\epsilon}\)</span> and fitted value vector <span class="math inline">\(\hat{y}\)</span> are orthogonal to each other.</p>
</section>
<section id="q1f" class="level4">
<h4 class="anchored" data-anchor-id="q1f">q1f</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Correlation of the residuals with income: "</span>,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">signif</span>(<span class="fu">cor</span>(<span class="fu">residuals</span>(lm_q1a), teengamb<span class="sc">$</span>income), <span class="dv">3</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Correlation of the residuals with income:  3.25e-17</code></pre>
</div>
</div>
<p>Yes, it will always be zero because geometrically, the OLS model projects the outcome vector <span class="math inline">\(y\)</span> onto the plane spanned by the set of all predictor variables. In our case, the <code>income</code> vector is part of that plane. Consequently, the fitted values vector <span class="math inline">\(\hat{y}\)</span> lies on this plane while the residuals vector <span class="math inline">\(\hat{\epsilon}\)</span> is orthogonal to the plane.</p>
</section>
<section id="q1g" class="level4">
<h4 class="anchored" data-anchor-id="q1g">q1g</h4>
<p>Female is coded as one and male is coded as zero.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"For females, the difference in average weekly gambling between females"</span>,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"and males, holding other factors constant, is"</span>,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">signif</span>(<span class="fu">summary</span>(lm_q1a)<span class="sc">$</span>coefficients[<span class="dv">2</span>], <span class="dv">3</span>),</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"pounds."</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>For females, the difference in average weekly gambling between females and males, holding other factors constant, is -22.1 pounds.</code></pre>
</div>
</div>
</section>
</section>
<section id="q2" class="level3">
<h3 class="anchored" data-anchor-id="q2">Q2</h3>
<section id="q2a" class="level4">
<h4 class="anchored" data-anchor-id="q2a">q2a</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(uswages, <span class="at">package =</span> <span class="st">"faraway"</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>lm_q2a <span class="ot">&lt;-</span> <span class="fu">lm</span>(wage <span class="sc">~</span> educ <span class="sc">+</span> exper, <span class="at">data =</span> uswages)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_q2a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wage ~ educ + exper, data = uswages)

Residuals:
    Min      1Q  Median      3Q     Max 
-1018.2  -237.9   -50.9   149.9  7228.6 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -242.7994    50.6816  -4.791 1.78e-06 ***
educ          51.1753     3.3419  15.313  &lt; 2e-16 ***
exper          9.7748     0.7506  13.023  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 427.9 on 1997 degrees of freedom
Multiple R-squared:  0.1351,    Adjusted R-squared:  0.1343 
F-statistic:   156 on 2 and 1997 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="q2b" class="level4">
<h4 class="anchored" data-anchor-id="q2b">q2b</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(uswages[, <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>], <span class="dv">2</span>, min)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> wage  educ exper 
50.39  0.00 -2.00 </code></pre>
</div>
</div>
</section>
<section id="q2c" class="level4">
<h4 class="anchored" data-anchor-id="q2c">q2c</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># When predictors are zero, the intercept is the prediction.</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Predicted wage for a worker with no education and no experience:"</span>,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">format</span>(<span class="fu">round</span>(<span class="fu">summary</span>(lm_q2a)<span class="sc">$</span>coef[<span class="dv">1</span>], <span class="dv">2</span>), <span class="at">nsmall =</span> <span class="dv">2</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Predicted wage for a worker with no education and no experience: -242.80</code></pre>
</div>
</div>
<p>It doesn’t make sense to report a negative wage value.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(uswages, educ <span class="sc">==</span> <span class="dv">0</span> <span class="sc">|</span> exper <span class="sc">==</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>         wage educ exper race smsa ne mw so we pt
12878  148.39   16     0    0    1  0  1  0  0  1
21572  308.64   16     0    0    1  0  0  1  0  0
6090   144.03   12     0    0    1  1  0  0  0  0
4310   493.83   14     0    0    1  1  0  0  0  0
6305    56.79   14     0    0    0  1  0  0  0  1
2245   830.96   18     0    0    1  1  0  0  0  0
3858   241.21   12     0    0    0  1  0  0  0  0
27419  142.45   12     0    0    1  0  0  0  1  0
10853  197.41   12     0    0    1  0  1  0  0  1
11576  283.95   16     0    0    1  0  1  0  0  0
27774  347.22   14     0    0    1  0  0  0  1  0
19834   61.73   13     0    0    0  0  0  1  0  1
20846  189.93   16     0    0    1  0  0  1  0  1
8006    56.98   14     0    0    0  0  1  0  0  1
27787  892.59   13     0    0    0  0  0  0  1  0
4014    78.56   14     0    0    0  1  0  0  0  1
27585  308.64   16     0    0    1  0  0  0  1  0
15354  335.10   12     0    0    1  0  0  1  0  0
18362  195.47   16     0    0    0  0  0  1  0  0
24439  159.10    0    27    0    0  0  0  0  1  0
3778   274.35   12     0    0    1  1  0  0  0  0
26303  189.93    0    54    0    1  0  0  0  1  0
6345    54.61   13     0    0    0  1  0  0  0  1
21435  106.08   14     0    0    0  0  0  1  0  1
4648   474.83   12     0    0    1  1  0  0  0  0
12401  174.90   14     0    0    0  0  1  0  0  1
24355  165.43   12     0    0    0  0  0  0  1  0
3881   474.83   18     0    0    0  1  0  0  0  0
21604  400.26    0    52    0    1  0  0  1  0  0
20410  246.91   16     0    0    0  0  0  1  0  1
27138   96.19   12     0    0    1  0  0  0  1  0
17129  308.64    0    47    1    1  0  0  1  0  0
10476  130.58   13     0    1    1  0  1  0  0  0
13803   52.23   14     0    1    1  0  0  1  0  1
8902    66.14   12     0    0    1  0  1  0  0  1
16915  143.87   12     0    0    1  0  0  1  0  1
2780  5144.03    0    18    0    1  1  0  0  0  0
13686  395.06    0    42    0    1  0  0  1  0  0
12711  205.76   15     0    0    1  0  1  0  0  0
15548  200.62   12     0    0    1  0  0  1  0  0
21269  284.90   13     0    0    1  0  0  1  0  1
26160  166.19   13     0    0    1  0  0  0  1  1
6148    74.07   12     0    0    1  1  0  0  0  0
1376   569.80   13     0    0    1  1  0  0  0  0
21479  237.42   16     0    1    0  0  0  1  0  1
3337   144.44   15     0    0    1  1  0  0  0  1
21367  100.78   13     0    0    1  0  0  1  0  1
8485   427.98   14     0    0    1  0  1  0  0  1
18047  154.32   13     0    0    1  0  0  1  0  0
27780   92.59   12     0    0    1  0  0  0  1  1
24297  216.05   15     0    0    1  0  0  0  1  0
8948    77.16   14     0    0    1  0  1  0  0  1
25196  227.02   15     0    0    1  0  0  0  1  1
14153  108.02   13     0    1    1  0  0  1  0  1
7651   284.90   16     0    0    0  0  1  0  0  1
21436  356.13    0    54    0    1  0  0  1  0  0
13754  197.22   16     0    0    1  0  0  1  0  1
1620   493.83   14     0    0    0  1  0  0  0  0
7739   465.80   18     0    0    1  0  1  0  0  0
5444    54.01   12     0    0    1  1  0  0  0  1
10738  102.88   12     0    0    1  0  1  0  0  1
26011   86.13   12     0    0    1  0  0  0  1  1
8235    85.66   13     0    1    1  0  1  0  0  1
22810  142.45   13     0    0    0  0  0  0  1  0
25047  593.54    0    56    0    1  0  0  0  1  0
12408  178.60   16     0    0    0  0  1  0  0  1</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(uswages, educ <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> exper <span class="sc">==</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] wage  educ  exper race  smsa  ne    mw    so    we    pt   
&lt;0 rows&gt; (or 0-length row.names)</code></pre>
</div>
</div>
<p>According to the above output, the data confirms that while some workers have either zero education or zero experience, no worker has both simultaneously.</p>
<p>Therefore, the model’s prediction for this scenario is a pure extrapolation, as it’s forecasting for a data point that does not exist in the dataset.</p>
</section>
<section id="q2d" class="level4">
<h4 class="anchored" data-anchor-id="q2d">q2d</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(<span class="fu">cor</span>(<span class="fu">predict</span>(lm_q2a), uswages<span class="sc">$</span>wage)<span class="sc">^</span><span class="dv">2</span>, <span class="fu">summary</span>(lm_q2a)<span class="sc">$</span>r.squared)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
</section>
<section id="q2e" class="level4">
<h4 class="anchored" data-anchor-id="q2e">q2e</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>lm_q2e <span class="ot">&lt;-</span> <span class="fu">lm</span>(wage <span class="sc">~</span> educ <span class="sc">+</span> exper <span class="sc">-</span> <span class="dv">1</span>, <span class="at">data =</span> uswages)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_q2e)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wage ~ educ + exper - 1, data = uswages)

Residuals:
   Min     1Q Median     3Q    Max 
-903.6 -254.9  -70.9  140.8 7144.6 

Coefficients:
      Estimate Std. Error t value Pr(&gt;|t|)    
educ    36.014      1.079   33.37   &lt;2e-16 ***
exper    7.854      0.638   12.31   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 430.2 on 1998 degrees of freedom
Multiple R-squared:  0.6819,    Adjusted R-squared:  0.6815 
F-statistic:  2141 on 2 and 1998 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><span class="math inline">\(R^2\)</span> has increased.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(<span class="fu">predict</span>(lm_q2e), uswages<span class="sc">$</span>wage)<span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1340295</code></pre>
</div>
</div>
<p>But direct calculation provides a similar value to the initial model.</p>
</section>
<section id="q2f" class="level4">
<h4 class="anchored" data-anchor-id="q2f">q2f</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"RSS of Initial Model:"</span>,</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">residuals</span>(lm_q2a)<span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"</span><span class="sc">\n</span><span class="st">RSS of Intercept Removed Model:"</span>,</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">residuals</span>(lm_q2e)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>RSS of Initial Model: 365568644 
RSS of Intercept Removed Model: 369769963</code></pre>
</div>
</div>
<p>RSS of Initial Model (More parameter, more flexibility) &lt; RSS of Intercept Removed Model (One less parameter)</p>
</section>
<section id="q2g" class="level4">
<h4 class="anchored" data-anchor-id="q2g">q2g</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">coef</span>(lm_q2a)[<span class="st">'educ'</span>], <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> educ 
51.18 </code></pre>
</div>
</div>
</section>
<section id="q2h" class="level4">
<h4 class="anchored" data-anchor-id="q2h">q2h</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>lm_q2h <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(wage) <span class="sc">~</span> educ <span class="sc">+</span> exper, <span class="at">data =</span> uswages)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_q2h)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(wage) ~ educ + exper, data = uswages)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.7533 -0.3495  0.1068  0.4381  3.5699 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 4.650319   0.078354   59.35   &lt;2e-16 ***
educ        0.090506   0.005167   17.52   &lt;2e-16 ***
exper       0.018079   0.001160   15.58   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6615 on 1997 degrees of freedom
Multiple R-squared:  0.1749,    Adjusted R-squared:  0.174 
F-statistic: 211.6 on 2 and 1997 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li>The <code>Residual standard error</code> is only 427.9 in the first model but in the logged response model, it is 0.6615 due to scaling.</li>
<li><span class="math inline">\(R^{2}_{\text{first model}} = 0.1351 &lt; R^{2}_{\text{logged model}} = 0.1749\)</span>
<ul>
<li>Since <span class="math inline">\(R^2\)</span> is unit free, the logged model is preferable.</li>
</ul></li>
</ul>
</section>
<section id="q2i" class="level4">
<h4 class="anchored" data-anchor-id="q2i">q2i</h4>
<p>First we need to know the value of <code>experience</code> on the unlogged wage scale by exponentiating both side.</p>
<p><span class="math display">\[
\text{wage} = e^{\beta_0 + \beta_1 \cdot \text{education} + \beta_2 \cdot \text{experience}}
\]</span></p>
<p><span class="math display">\[
\text{wage} = e^{\beta_0} \times e^{\beta_1 \cdot \text{education}} \times e^{\beta_2 \cdot \text{experience}}
\]</span></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Need to unlogged the scaled wage values</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">exp</span>(<span class="fu">coef</span>(lm_q2h)[<span class="st">'educ'</span>]), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>educ 
1.09 </code></pre>
</div>
</div>
<p>An increase of one in education corresponds to multiplying the predicted response by <span class="math inline">\(1.09\)</span>. This indicates that if education were to be increased by one, holding experience constant, we expect a 9% increase in wage.</p>
</section>
<section id="q2j" class="level4">
<h4 class="anchored" data-anchor-id="q2j">q2j</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>lm_q2j <span class="ot">&lt;-</span> <span class="fu">lm</span>(wage <span class="sc">~</span> educ <span class="sc">+</span> exper <span class="sc">+</span> ne <span class="sc">+</span> mw <span class="sc">+</span> we <span class="sc">+</span> so, <span class="at">data =</span> uswages)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_q2j)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = wage ~ educ + exper + ne + mw + we + so, data = uswages)

Residuals:
   Min     1Q Median     3Q    Max 
-993.7 -238.8  -46.1  149.2 7244.1 

Coefficients: (1 not defined because of singularities)
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -259.9178    51.9863  -5.000 6.24e-07 ***
educ          51.0931     3.3448  15.275  &lt; 2e-16 ***
exper          9.8068     0.7507  13.064  &lt; 2e-16 ***
ne            23.8538    26.3327   0.906   0.3651    
mw            -7.3453    25.7230  -0.286   0.7753    
we            66.5168    26.9880   2.465   0.0138 *  
so                 NA         NA      NA       NA    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 427.3 on 1994 degrees of freedom
Multiple R-squared:  0.1387,    Adjusted R-squared:  0.1366 
F-statistic: 64.24 on 5 and 1994 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Lack of identifiability.</p>
</section>
<section id="q2k" class="level4">
<h4 class="anchored" data-anchor-id="q2k">q2k</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>rowsum <span class="ot">&lt;-</span> uswages<span class="sc">$</span>ne <span class="sc">+</span> uswages<span class="sc">$</span>mw <span class="sc">+</span> uswages<span class="sc">$</span>we <span class="sc">+</span> uswages<span class="sc">$</span>so</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(rowsum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 1 1 1 1 1</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(rowsum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<ul>
<li>All four regional indicators sum to one because all mean are in one and only one region, thus by including all four indicators in the same model will run into the identifiability problem.</li>
<li>To resolve this, either drop one of the variable or drop the intercept term from the model.</li>
</ul>
</section>
</section>
<section id="q3" class="level3">
<h3 class="anchored" data-anchor-id="q3">Q3</h3>
<section id="q3a" class="level4">
<h4 class="anchored" data-anchor-id="q3a">q3a</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(prostate, <span class="at">package =</span> <span class="st">"faraway"</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(prostate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      lcavol lweight age      lbph svi      lcp gleason pgg45     lpsa
1 -0.5798185  2.7695  50 -1.386294   0 -1.38629       6     0 -0.43078
2 -0.9942523  3.3196  58 -1.386294   0 -1.38629       6     0 -0.16252
3 -0.5108256  2.6912  74 -1.386294   0 -1.38629       7    20 -0.16252
4 -1.2039728  3.2828  58 -1.386294   0 -1.38629       6     0 -0.16252
5  0.7514161  3.4324  62 -1.386294   0 -1.38629       6     0  0.37156
6 -1.0498221  3.2288  50 -1.386294   0 -1.38629       6     0  0.76547</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>lm_q3a <span class="ot">&lt;-</span> <span class="fu">lm</span>(lpsa <span class="sc">~</span> lcavol, <span class="at">data =</span> prostate)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>lm_q3a_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(lm_q3a)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(lm_q3a_summary[<span class="fu">c</span>(<span class="st">'sigma'</span>, <span class="st">'r.squared'</span>)], round, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    sigma r.squared 
     0.79      0.54 </code></pre>
</div>
</div>
<p><span class="math inline">\(\sigma = 0.79\)</span> <span class="math inline">\(R^2 = 0.54\)</span></p>
</section>
<section id="q3b" class="level4">
<h4 class="anchored" data-anchor-id="q3b">q3b</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>sigmas <span class="ot">&lt;-</span> lm_q3a_summary<span class="sc">$</span>sigma</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>rsquares <span class="ot">&lt;-</span> lm_q3a_summary<span class="sc">$</span>r.squared</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>lm_q3b <span class="ot">&lt;-</span> <span class="fu">lm</span>(lpsa <span class="sc">~</span> lcavol <span class="sc">+</span> lweight, <span class="at">data =</span> prostate)</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>lm_q3b_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(lm_q3b)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>sigmas <span class="ot">&lt;-</span> <span class="fu">c</span>(sigmas, lm_q3b_summary<span class="sc">$</span>sigma)</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>rsquares <span class="ot">&lt;-</span> <span class="fu">c</span>(rsquares, lm_q3b_summary<span class="sc">$</span>r.squared)</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>lm_q3b <span class="ot">&lt;-</span> <span class="fu">lm</span>(lpsa <span class="sc">~</span> lcavol <span class="sc">+</span> lweight <span class="sc">+</span> svi, <span class="at">data =</span> prostate)</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>lm_q3b_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(lm_q3b)</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>sigmas <span class="ot">&lt;-</span> <span class="fu">c</span>(sigmas, lm_q3b_summary<span class="sc">$</span>sigma)</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>rsquares <span class="ot">&lt;-</span> <span class="fu">c</span>(rsquares, lm_q3b_summary<span class="sc">$</span>r.squared)</span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a>lm_q3b <span class="ot">&lt;-</span> <span class="fu">lm</span>(lpsa <span class="sc">~</span> lcavol <span class="sc">+</span> lweight <span class="sc">+</span> svi <span class="sc">+</span> lbph, <span class="at">data =</span> prostate)</span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a>lm_q3b_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(lm_q3b)</span>
<span id="cb49-16"><a href="#cb49-16" aria-hidden="true" tabindex="-1"></a>sigmas <span class="ot">&lt;-</span> <span class="fu">c</span>(sigmas, lm_q3b_summary<span class="sc">$</span>sigma)</span>
<span id="cb49-17"><a href="#cb49-17" aria-hidden="true" tabindex="-1"></a>rsquares <span class="ot">&lt;-</span> <span class="fu">c</span>(rsquares, lm_q3b_summary<span class="sc">$</span>r.squared)</span>
<span id="cb49-18"><a href="#cb49-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-19"><a href="#cb49-19" aria-hidden="true" tabindex="-1"></a>lm_q3b <span class="ot">&lt;-</span> <span class="fu">lm</span>(lpsa <span class="sc">~</span> lcavol <span class="sc">+</span> lweight <span class="sc">+</span> svi <span class="sc">+</span> lbph <span class="sc">+</span> age, <span class="at">data =</span> prostate)</span>
<span id="cb49-20"><a href="#cb49-20" aria-hidden="true" tabindex="-1"></a>lm_q3b_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(lm_q3b)</span>
<span id="cb49-21"><a href="#cb49-21" aria-hidden="true" tabindex="-1"></a>sigmas <span class="ot">&lt;-</span> <span class="fu">c</span>(sigmas, lm_q3b_summary<span class="sc">$</span>sigma)</span>
<span id="cb49-22"><a href="#cb49-22" aria-hidden="true" tabindex="-1"></a>rsquares <span class="ot">&lt;-</span> <span class="fu">c</span>(rsquares, lm_q3b_summary<span class="sc">$</span>r.squared)</span>
<span id="cb49-23"><a href="#cb49-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-24"><a href="#cb49-24" aria-hidden="true" tabindex="-1"></a>lm_q3b <span class="ot">&lt;-</span> <span class="fu">lm</span>(lpsa <span class="sc">~</span> lcavol <span class="sc">+</span> lweight <span class="sc">+</span> svi <span class="sc">+</span> lbph <span class="sc">+</span> age <span class="sc">+</span> lcp, <span class="at">data =</span> prostate)</span>
<span id="cb49-25"><a href="#cb49-25" aria-hidden="true" tabindex="-1"></a>lm_q3b_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(lm_q3b)</span>
<span id="cb49-26"><a href="#cb49-26" aria-hidden="true" tabindex="-1"></a>sigmas <span class="ot">&lt;-</span> <span class="fu">c</span>(sigmas, lm_q3b_summary<span class="sc">$</span>sigma)</span>
<span id="cb49-27"><a href="#cb49-27" aria-hidden="true" tabindex="-1"></a>rsquares <span class="ot">&lt;-</span> <span class="fu">c</span>(rsquares, lm_q3b_summary<span class="sc">$</span>r.squared)</span>
<span id="cb49-28"><a href="#cb49-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-29"><a href="#cb49-29" aria-hidden="true" tabindex="-1"></a>lm_q3b <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb49-30"><a href="#cb49-30" aria-hidden="true" tabindex="-1"></a>  lpsa <span class="sc">~</span> lcavol <span class="sc">+</span> lweight <span class="sc">+</span> svi <span class="sc">+</span> lbph <span class="sc">+</span> age <span class="sc">+</span> lcp <span class="sc">+</span> pgg45,</span>
<span id="cb49-31"><a href="#cb49-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> prostate</span>
<span id="cb49-32"><a href="#cb49-32" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb49-33"><a href="#cb49-33" aria-hidden="true" tabindex="-1"></a>lm_q3b_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(lm_q3b)</span>
<span id="cb49-34"><a href="#cb49-34" aria-hidden="true" tabindex="-1"></a>sigmas <span class="ot">&lt;-</span> <span class="fu">c</span>(sigmas, lm_q3b_summary<span class="sc">$</span>sigma)</span>
<span id="cb49-35"><a href="#cb49-35" aria-hidden="true" tabindex="-1"></a>rsquares <span class="ot">&lt;-</span> <span class="fu">c</span>(rsquares, lm_q3b_summary<span class="sc">$</span>r.squared)</span>
<span id="cb49-36"><a href="#cb49-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-37"><a href="#cb49-37" aria-hidden="true" tabindex="-1"></a>lm_q3b <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb49-38"><a href="#cb49-38" aria-hidden="true" tabindex="-1"></a>  lpsa <span class="sc">~</span> lcavol <span class="sc">+</span> lweight <span class="sc">+</span> svi <span class="sc">+</span> lbph <span class="sc">+</span> age <span class="sc">+</span> lcp <span class="sc">+</span> pgg45 <span class="sc">+</span> gleason,</span>
<span id="cb49-39"><a href="#cb49-39" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> prostate</span>
<span id="cb49-40"><a href="#cb49-40" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb49-41"><a href="#cb49-41" aria-hidden="true" tabindex="-1"></a>lm_q3b_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(lm_q3b)</span>
<span id="cb49-42"><a href="#cb49-42" aria-hidden="true" tabindex="-1"></a>sigmas <span class="ot">&lt;-</span> <span class="fu">c</span>(sigmas, lm_q3b_summary<span class="sc">$</span>sigma)</span>
<span id="cb49-43"><a href="#cb49-43" aria-hidden="true" tabindex="-1"></a>rsquares <span class="ot">&lt;-</span> <span class="fu">c</span>(rsquares, lm_q3b_summary<span class="sc">$</span>r.squared)</span>
<span id="cb49-44"><a href="#cb49-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-45"><a href="#cb49-45" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(<span class="fu">data.frame</span>(<span class="at">npreds =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>, sigmas, rsquares), round, <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     npreds sigmas rsquares
[1,]      1 0.7875   0.5394
[2,]      2 0.7506   0.5859
[3,]      3 0.7168   0.6264
[4,]      4 0.7108   0.6366
[5,]      5 0.7073   0.6441
[6,]      6 0.7102   0.6451
[7,]      7 0.7048   0.6544
[8,]      8 0.7084   0.6548</code></pre>
</div>
</div>
</section>
<section id="q3c" class="level4">
<h4 class="anchored" data-anchor-id="q3c">q3c</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>,</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  sigmas,</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Number of Predictors"</span>,</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Residual Standard Error"</span>,</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"l"</span></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The RSE shows a sharp initial decrease with the number of predictors. The reduction continues, though not monotonically, reaching its minimum value when 7 predictors are included.”</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>,</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  rsquares,</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Number of Predictors"</span>,</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"R-Squared"</span>,</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"l"</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Because the Residual Sum of Squares (RSS) can only decrease or stay the same when predictors are added, R-squared is monotonically non-decreasing with the number of predictors</p>
</section>
</section>
<section id="q4" class="level3">
<h3 class="anchored" data-anchor-id="q4">Q4</h3>
<section id="q4a" class="level4">
<h4 class="anchored" data-anchor-id="q4a">q4a</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>lm_q4a_i <span class="ot">&lt;-</span> <span class="fu">lm</span>(lpsa <span class="sc">~</span> lcavol, <span class="at">data =</span> prostate)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>lm_q4a_ii <span class="ot">&lt;-</span> <span class="fu">lm</span>(lcavol <span class="sc">~</span> lpsa, <span class="at">data =</span> prostate)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lpsa <span class="sc">~</span> lcavol, <span class="at">data =</span> prostate)</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(lm_q4a_i)</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">a =</span> <span class="sc">-</span><span class="fu">coef</span>(lm_q4a_ii)[<span class="dv">1</span>] <span class="sc">/</span> <span class="fu">coef</span>(lm_q4a_ii)[<span class="dv">2</span>],</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">b =</span> <span class="dv">1</span> <span class="sc">/</span> <span class="fu">coef</span>(lm_q4a_ii)[<span class="dv">2</span>],</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="st">"red"</span></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>mean_lcavol <span class="ot">=</span> <span class="fu">mean</span>(prostate<span class="sc">$</span>lcavol)</span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a>mean_lpsa <span class="ot">=</span> <span class="fu">mean</span>(prostate<span class="sc">$</span>lpsa)</span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(</span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> mean_lcavol,</span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> mean_lpsa,</span>
<span id="cb53-18"><a href="#cb53-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb53-19"><a href="#cb53-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="st">"darkgreen"</span>,</span>
<span id="cb53-20"><a href="#cb53-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">cex =</span> <span class="fl">2.5</span></span>
<span id="cb53-21"><a href="#cb53-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb53-22"><a href="#cb53-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-23"><a href="#cb53-23" aria-hidden="true" tabindex="-1"></a>label_text <span class="ot">=</span> <span class="fu">paste</span>(</span>
<span id="cb53-24"><a href="#cb53-24" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Mean (x̄, ȳ): ("</span>,</span>
<span id="cb53-25"><a href="#cb53-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(mean_lcavol, <span class="dv">2</span>),</span>
<span id="cb53-26"><a href="#cb53-26" aria-hidden="true" tabindex="-1"></a>  <span class="st">", "</span>,</span>
<span id="cb53-27"><a href="#cb53-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(mean_lpsa, <span class="dv">2</span>),</span>
<span id="cb53-28"><a href="#cb53-28" aria-hidden="true" tabindex="-1"></a>  <span class="st">")"</span>,</span>
<span id="cb53-29"><a href="#cb53-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">sep =</span> <span class="st">""</span></span>
<span id="cb53-30"><a href="#cb53-30" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb53-31"><a href="#cb53-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-32"><a href="#cb53-32" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(</span>
<span id="cb53-33"><a href="#cb53-33" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="sc">-</span><span class="fl">0.1</span>, <span class="co"># X-coordinate: Place it near the left side of the plot</span></span>
<span id="cb53-34"><a href="#cb53-34" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="dv">3</span>, <span class="co"># Y-coordinate: Place it near the top of the plot</span></span>
<span id="cb53-35"><a href="#cb53-35" aria-hidden="true" tabindex="-1"></a>  <span class="at">labels =</span> label_text,</span>
<span id="cb53-36"><a href="#cb53-36" aria-hidden="true" tabindex="-1"></a>  <span class="at">col =</span> <span class="st">"darkgreen"</span>, <span class="co"># Set a distinct color</span></span>
<span id="cb53-37"><a href="#cb53-37" aria-hidden="true" tabindex="-1"></a>  <span class="at">adj =</span> <span class="dv">0</span>, <span class="co"># Left-align the text (0 = left, 0.5 = center, 1 = right)</span></span>
<span id="cb53-38"><a href="#cb53-38" aria-hidden="true" tabindex="-1"></a>  <span class="at">cex =</span> <span class="fl">1.5</span> <span class="co"># Character expansion (text size)</span></span>
<span id="cb53-39"><a href="#cb53-39" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter2_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Since it is a <code>lpsa</code> against <code>lcavol</code> plot, we cannot simply call <code>abline(lm(lcavol ~ lpsa, data = prostate))</code> for the second regression line since <code>lm(lcavol ~ lpsa, data = prostate)</code> predicts <span class="math inline">\(x\)</span> from <span class="math inline">\(y\)</span>, that is, <span class="math inline">\(x = a + by\)</span>. Thus, to plot it against the existing <span class="math inline">\(y\)</span> vs <span class="math inline">\(x\)</span> plot, the equation needs to be re-arranged to:</p>
<p><span class="math display">\[x = a + by\]</span></p>
<p><span class="math display">\[by = x - a\]</span></p>
<p><span class="math display">\[y = \frac{-a + x}{b}\]</span></p>
<p><span class="math display">\[y = \frac{-a}{b} + \frac{1}{b} \cdot x\]</span></p>
<p>Since <span class="math inline">\(a\)</span> is the intercept and <span class="math inline">\(b\)</span> is the slope.</p>
<p>The point of intersection for these two regression lines is the point of the means <span class="math inline">\(\bar{x}, \bar{y}\)</span> because this point is a fundamental property of any simple linear regression model calculated using the Ordinary Least Squares (OLS) method.</p>
</section>
</section>
<section id="q5" class="level3">
<h3 class="anchored" data-anchor-id="q5">Q5</h3>
<section id="q5a" class="level4">
<h4 class="anchored" data-anchor-id="q5a">q5a</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(cheddar, <span class="at">package =</span> <span class="st">"faraway"</span>)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(cheddar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  taste Acetic   H2S Lactic
1  12.3  4.543 3.135   0.86
2  20.9  5.159 5.043   1.53
3  39.0  5.366 5.438   1.57
4  47.9  5.759 7.496   1.81
5   5.6  4.663 3.807   0.99
6  25.9  5.697 7.601   1.09</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>lm_q5a <span class="ot">&lt;-</span> <span class="fu">lm</span>(taste <span class="sc">~</span> Acetic <span class="sc">+</span> H2S <span class="sc">+</span> Lactic, <span class="at">data =</span> cheddar)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_q5a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = taste ~ Acetic + H2S + Lactic, data = cheddar)

Residuals:
    Min      1Q  Median      3Q     Max 
-17.390  -6.612  -1.009   4.908  25.449 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) -28.8768    19.7354  -1.463  0.15540   
Acetic        0.3277     4.4598   0.073  0.94198   
H2S           3.9118     1.2484   3.133  0.00425 **
Lactic       19.6705     8.6291   2.280  0.03108 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 10.13 on 26 degrees of freedom
Multiple R-squared:  0.6518,    Adjusted R-squared:  0.6116 
F-statistic: 16.22 on 3 and 26 DF,  p-value: 3.81e-06</code></pre>
</div>
</div>
</section>
<section id="q5b" class="level4">
<h4 class="anchored" data-anchor-id="q5b">q5b</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(<span class="fu">fitted</span>(lm_q5a), cheddar<span class="sc">$</span>taste)<span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6517747</code></pre>
</div>
</div>
<p>This value appears in as the <span class="math inline">\(R^2\)</span> of <code>lm_q5a</code>’s output.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">near</span>(<span class="fu">summary</span>(lm_q5a)<span class="sc">$</span>r.squared, <span class="fu">cor</span>(<span class="fu">fitted</span>(lm_q5a), cheddar<span class="sc">$</span>taste)<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
</section>
<section id="q5c" class="level4">
<h4 class="anchored" data-anchor-id="q5c">q5c</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>lm_q5c <span class="ot">&lt;-</span> <span class="fu">lm</span>(taste <span class="sc">~</span> Acetic <span class="sc">+</span> H2S <span class="sc">+</span> Lactic <span class="sc">-</span> <span class="dv">1</span>, <span class="at">data =</span> cheddar)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(lm_q5c)<span class="sc">$</span>r.squared, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.888</code></pre>
</div>
</div>
<p>Without the intercept term, <span class="math inline">\(R^2 = 0.888\)</span>.</p>
<p>When compared to the correlation between the fitted values and the response squared, the latter is a much more plausible value.</p>
<p>####q5d</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> Acetic <span class="sc">+</span> H2S <span class="sc">+</span> Lactic,</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> cheddar</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> cheddar<span class="sc">$</span>taste</span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>qrx <span class="ot">&lt;-</span> <span class="fu">qr</span>(X)</span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a>f <span class="ot">=</span> <span class="fu">t</span>(<span class="fu">qr.Q</span>(qrx)) <span class="sc">%*%</span> y</span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a><span class="fu">backsolve</span>(<span class="fu">qr.R</span>(qrx), f)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            [,1]
[1,] -28.8767696
[2,]   0.3277413
[3,]   3.9118411
[4,]  19.6705434</code></pre>
</div>
</div>
</section>
</section>
<section id="q6" class="level3">
<h3 class="anchored" data-anchor-id="q6">Q6</h3>
<section id="q6a" class="level4">
<h4 class="anchored" data-anchor-id="q6a">q6a</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(wafer, <span class="at">package =</span> <span class="st">"faraway"</span>)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(wafer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  x1 x2 x3 x4 resist
1  -  -  -  -  193.4
2  +  -  -  -  247.6
3  -  +  -  -  168.2
4  +  +  -  -  205.0
5  -  -  +  -  303.4
6  +  -  +  -  339.9</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>lm_q6a <span class="ot">&lt;-</span> <span class="fu">lm</span>(resist <span class="sc">~</span> x1 <span class="sc">+</span> x2 <span class="sc">+</span> x3 <span class="sc">+</span> x4, <span class="at">data =</span> wafer)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_q6a, <span class="at">cor =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = resist ~ x1 + x2 + x3 + x4, data = wafer)

Residuals:
    Min      1Q  Median      3Q     Max 
-43.381 -17.119   4.825  16.644  33.769 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   236.78      14.77  16.032 5.65e-09 ***
x1+            25.76      13.21   1.950 0.077085 .  
x2+           -69.89      13.21  -5.291 0.000256 ***
x3+            43.59      13.21   3.300 0.007083 ** 
x4+           -14.49      13.21  -1.097 0.296193    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 26.42 on 11 degrees of freedom
Multiple R-squared:  0.7996,    Adjusted R-squared:  0.7267 
F-statistic: 10.97 on 4 and 11 DF,  p-value: 0.0007815

Correlation of Coefficients:
    (Intercept) x1+   x2+   x3+  
x1+ -0.45                        
x2+ -0.45        0.00            
x3+ -0.45        0.00  0.00      
x4+ -0.45        0.00  0.00  0.00</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(lm_q6a)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(X)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept) x1+ x2+ x3+ x4+
1           1   0   0   0   0
2           1   1   0   0   0
3           1   0   1   0   0
4           1   1   1   0   0
5           1   0   0   1   0
6           1   1   0   1   0</code></pre>
</div>
</div>
<p>The function automatically coded <code>-</code> and <code>+</code> as <span class="math inline">\(0\)</span> and <span class="math inline">\(1\)</span> respectively.</p>
</section>
<section id="q6b" class="level4">
<h4 class="anchored" data-anchor-id="q6b">q6b</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(X)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor(X): the standard deviation is zero</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>            (Intercept) x1+ x2+ x3+ x4+
(Intercept)           1  NA  NA  NA  NA
x1+                  NA   1   0   0   0
x2+                  NA   0   1   0   0
x3+                  NA   0   0   1   0
x4+                  NA   0   0   0   1</code></pre>
</div>
</div>
<p>The missing values are due to the intercept being constant across all observations. A constant variable has a standard deviation of zero. Because the correlation coefficient formula requires dividing by the product of the two variables’ standard deviations, the zero value in the denominator makes the correlation mathematically undefined.</p>
<p>In other words:</p>
<p><span class="math display">\[\bar{x} = \frac{1 + 1 + 1 + \ldots}{n} = 1\]</span></p>
<p><span class="math display">\[\sigma = \sqrt{\frac{\sum{(x_i - \bar{x})^2}}{n - 1}}\]</span></p>
<p><span class="math display">\[\sigma = \sqrt{\frac{\sum{(1 - 1)^2}}{n - 1}} = \sqrt{\frac{\sum{(0)^2}}{n - 1}} = 0\]</span></p>
<p>Given the formula:</p>
<p><span class="math display">\[\text{Correlation} = \frac{cov(x, y)}{\sigma_x \sigma_y}\]</span></p>
<p>we can see that when the denominator is <span class="math inline">\(0\)</span>, it will leads to a division by zero error.</p>
</section>
<section id="q6c" class="level4">
<h4 class="anchored" data-anchor-id="q6c">q6c</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(lm_q6a)<span class="sc">$</span>coefficients[<span class="dv">2</span>], <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 25.76</code></pre>
</div>
</div>
<p>An increase in 25.76.</p>
</section>
<section id="q6d" class="level4">
<h4 class="anchored" data-anchor-id="q6d">q6d</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>lm_q6d <span class="ot">&lt;-</span> <span class="fu">lm</span>(resist <span class="sc">~</span> x1 <span class="sc">+</span> x2 <span class="sc">+</span> x3, <span class="at">data =</span> wafer)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_q6d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = resist ~ x1 + x2 + x3, data = wafer)

Residuals:
    Min      1Q  Median      3Q     Max 
-36.137 -20.550   3.575  18.463  41.012 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   229.54      13.32  17.231 7.88e-10 ***
x1+            25.76      13.32   1.934 0.077047 .  
x2+           -69.89      13.32  -5.246 0.000206 ***
x3+            43.59      13.32   3.272 0.006677 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 26.64 on 12 degrees of freedom
Multiple R-squared:  0.7777,    Adjusted R-squared:  0.7221 
F-statistic: 13.99 on 3 and 12 DF,  p-value: 0.0003187</code></pre>
</div>
</div>
<ul>
<li>Estimates for <code>x1</code>, <code>x2</code>, and <code>x3</code> remain the same, but the intercept term’s estimate has slightly decreased.</li>
<li>Standard errors have increased slightly for all estimands.</li>
</ul>
</section>
<section id="q6e" class="level4">
<h4 class="anchored" data-anchor-id="q6e">q6e</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_q6a, <span class="at">cor =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = resist ~ x1 + x2 + x3 + x4, data = wafer)

Residuals:
    Min      1Q  Median      3Q     Max 
-43.381 -17.119   4.825  16.644  33.769 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   236.78      14.77  16.032 5.65e-09 ***
x1+            25.76      13.21   1.950 0.077085 .  
x2+           -69.89      13.21  -5.291 0.000256 ***
x3+            43.59      13.21   3.300 0.007083 ** 
x4+           -14.49      13.21  -1.097 0.296193    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 26.42 on 11 degrees of freedom
Multiple R-squared:  0.7996,    Adjusted R-squared:  0.7267 
F-statistic: 10.97 on 4 and 11 DF,  p-value: 0.0007815

Correlation of Coefficients:
    (Intercept) x1+   x2+   x3+  
x1+ -0.45                        
x2+ -0.45        0.00            
x3+ -0.45        0.00  0.00      
x4+ -0.45        0.00  0.00  0.00</code></pre>
</div>
</div>
<p>The design matrix <span class="math inline">\(X\)</span> is orthogonal, as evidenced by the zero off-diagonal entries in its correlation matrix. Orthogonality ensures that the estimated effect of each predictor is decoupled from the others. Therefore, the coefficient estimate for any given predictor is invariant to the inclusion or exclusion of other predictors in the model.</p>
</section>
</section>
<section id="q7" class="level3">
<h3 class="anchored" data-anchor-id="q7">Q7</h3>
<section id="q7a" class="level4">
<h4 class="anchored" data-anchor-id="q7a">q7a</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(truck, <span class="at">package =</span> <span class="st">"faraway"</span>)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(truck)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  B C D E O height
1 - - - - -   7.78
2 + - - + -   8.15
3 - + - + -   7.50
4 + + - - -   7.59
5 - - + + -   7.94
6 + - + - -   7.69</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>truck<span class="sc">$</span>B <span class="ot">&lt;-</span> <span class="fu">sapply</span>(truck<span class="sc">$</span>B, <span class="cf">function</span>(x) <span class="fu">ifelse</span>(x <span class="sc">==</span> <span class="st">"-"</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>truck<span class="sc">$</span>C <span class="ot">&lt;-</span> <span class="fu">sapply</span>(truck<span class="sc">$</span>C, <span class="cf">function</span>(x) <span class="fu">ifelse</span>(x <span class="sc">==</span> <span class="st">"-"</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>truck<span class="sc">$</span>D <span class="ot">&lt;-</span> <span class="fu">sapply</span>(truck<span class="sc">$</span>D, <span class="cf">function</span>(x) <span class="fu">ifelse</span>(x <span class="sc">==</span> <span class="st">"-"</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>truck<span class="sc">$</span>E <span class="ot">&lt;-</span> <span class="fu">sapply</span>(truck<span class="sc">$</span>E, <span class="cf">function</span>(x) <span class="fu">ifelse</span>(x <span class="sc">==</span> <span class="st">"-"</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a>truck<span class="sc">$</span>O <span class="ot">&lt;-</span> <span class="fu">sapply</span>(truck<span class="sc">$</span>O, <span class="cf">function</span>(x) <span class="fu">ifelse</span>(x <span class="sc">==</span> <span class="st">"-"</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>lm_q7a <span class="ot">&lt;-</span> <span class="fu">lm</span>(height <span class="sc">~</span> B <span class="sc">+</span> C <span class="sc">+</span> D <span class="sc">+</span> E <span class="sc">+</span> O, <span class="at">data =</span> truck)</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_q7a, <span class="at">cor =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = height ~ B + C + D + E + O, data = truck)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.33125 -0.09427  0.01625  0.11917  0.25875 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  7.63604    0.02291 333.316  &lt; 2e-16 ***
B            0.11062    0.02291   4.829 1.85e-05 ***
C           -0.08813    0.02291  -3.847   0.0004 ***
D           -0.01437    0.02291  -0.627   0.5337    
E            0.05187    0.02291   2.264   0.0288 *  
O           -0.12979    0.02291  -5.665 1.20e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1587 on 42 degrees of freedom
Multiple R-squared:  0.6433,    Adjusted R-squared:  0.6008 
F-statistic: 15.15 on 5 and 42 DF,  p-value: 1.681e-08

Correlation of Coefficients:
  (Intercept) B    C    D    E   
B 0.00                           
C 0.00        0.00               
D 0.00        0.00 0.00          
E 0.00        0.00 0.00 0.00     
O 0.00        0.00 0.00 0.00 0.00</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lm_q7a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)           B           C           D           E           O 
  7.6360417   0.1106250  -0.0881250  -0.0143750   0.0518750  -0.1297917 </code></pre>
</div>
</div>
</section>
<section id="q7b" class="level4">
<h4 class="anchored" data-anchor-id="q7b">q7b</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>lm_q7b <span class="ot">&lt;-</span> <span class="fu">lm</span>(height <span class="sc">~</span> B <span class="sc">+</span> C <span class="sc">+</span> D <span class="sc">+</span> E, <span class="at">data =</span> truck)</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_q7b, <span class="at">cor =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = height ~ B + C + D + E, data = truck)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.46104 -0.12479 -0.00479  0.14396  0.34896 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  7.63604    0.03007 253.915  &lt; 2e-16 ***
B            0.11062    0.03007   3.679 0.000648 ***
C           -0.08813    0.03007  -2.930 0.005402 ** 
D           -0.01437    0.03007  -0.478 0.635071    
E            0.05187    0.03007   1.725 0.091717 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2084 on 43 degrees of freedom
Multiple R-squared:  0.3706,    Adjusted R-squared:  0.3121 
F-statistic: 6.331 on 4 and 43 DF,  p-value: 0.0004258

Correlation of Coefficients:
  (Intercept) B    C    D   
B 0.00                      
C 0.00        0.00          
D 0.00        0.00 0.00     
E 0.00        0.00 0.00 0.00</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lm_q7b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)           B           C           D           E 
   7.636042    0.110625   -0.088125   -0.014375    0.051875 </code></pre>
</div>
</div>
<p>The coefficients remains unchanged.</p>
<p>Examining the <span class="math inline">\(X\)</span> matrix:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(<span class="fu">model.matrix</span>(lm_q7a))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor(model.matrix(lm_q7a)): the standard deviation is zero</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>            (Intercept)  B  C  D  E  O
(Intercept)           1 NA NA NA NA NA
B                    NA  1  0  0  0  0
C                    NA  0  1  0  0  0
D                    NA  0  0  1  0  0
E                    NA  0  0  0  1  0
O                    NA  0  0  0  0  1</code></pre>
</div>
</div>
<p>The design matrix <span class="math inline">\(X\)</span> is orthogonal, as evidenced by the zero off-diagonal entries in its correlation matrix</p>
</section>
<section id="q7c" class="level4">
<h4 class="anchored" data-anchor-id="q7c">q7c</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>truck_transformed <span class="ot">&lt;-</span> <span class="fu">transform</span>(truck, <span class="at">A =</span> B <span class="sc">+</span> C <span class="sc">+</span> D <span class="sc">+</span> E)</span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(truck_transformed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   B  C  D  E  O height  A
1 -1 -1 -1 -1 -1   7.78 -4
2  1 -1 -1  1 -1   8.15  0
3 -1  1 -1  1 -1   7.50  0
4  1  1 -1 -1 -1   7.59  0
5 -1 -1  1  1 -1   7.94  0
6  1 -1  1 -1 -1   7.69  0</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>lm_q7c <span class="ot">&lt;-</span> <span class="fu">lm</span>(height <span class="sc">~</span> A <span class="sc">+</span> B <span class="sc">+</span> C <span class="sc">+</span> D <span class="sc">+</span> E <span class="sc">+</span> O, <span class="at">data =</span> truck_transformed)</span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lm_q7c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)           A           B           C           D           E 
  7.6360417   0.0518750   0.0587500  -0.1400000  -0.0662500          NA 
          O 
 -0.1297917 </code></pre>
</div>
</div>
<p>E is not estimable; A = B + C + D + E makes the predictors collinear, so R excluded E due to identifiability issues (<em>from pg31: Predictors occurring later in the model formula are preferred for removal …</em>)</p>
</section>
<section id="q7d" class="level4">
<h4 class="anchored" data-anchor-id="q7d">q7d</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(lm_q7c)</span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>X</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept)  A  B  C  D  E  O
1            1 -4 -1 -1 -1 -1 -1
2            1  0  1 -1 -1  1 -1
3            1  0 -1  1 -1  1 -1
4            1  0  1  1 -1 -1 -1
5            1  0 -1 -1  1  1 -1
6            1  0  1 -1  1 -1 -1
7            1  0 -1  1  1 -1 -1
8            1  4  1  1  1  1 -1
9            1 -4 -1 -1 -1 -1  1
10           1  0  1 -1 -1  1  1
11           1  0 -1  1 -1  1  1
12           1  0  1  1 -1 -1  1
13           1  0 -1 -1  1  1  1
14           1  0  1 -1  1 -1  1
15           1  0 -1  1  1 -1  1
16           1  4  1  1  1  1  1
17           1 -4 -1 -1 -1 -1 -1
18           1  0  1 -1 -1  1 -1
19           1  0 -1  1 -1  1 -1
20           1  0  1  1 -1 -1 -1
21           1  0 -1 -1  1  1 -1
22           1  0  1 -1  1 -1 -1
23           1  0 -1  1  1 -1 -1
24           1  4  1  1  1  1 -1
25           1 -4 -1 -1 -1 -1  1
26           1  0  1 -1 -1  1  1
27           1  0 -1  1 -1  1  1
28           1  0  1  1 -1 -1  1
29           1  0 -1 -1  1  1  1
30           1  0  1 -1  1 -1  1
31           1  0 -1  1  1 -1  1
32           1  4  1  1  1  1  1
33           1 -4 -1 -1 -1 -1 -1
34           1  0  1 -1 -1  1 -1
35           1  0 -1  1 -1  1 -1
36           1  0  1  1 -1 -1 -1
37           1  0 -1 -1  1  1 -1
38           1  0  1 -1  1 -1 -1
39           1  0 -1  1  1 -1 -1
40           1  4  1  1  1  1 -1
41           1 -4 -1 -1 -1 -1  1
42           1  0  1 -1 -1  1  1
43           1  0 -1  1 -1  1  1
44           1  0  1  1 -1 -1  1
45           1  0 -1 -1  1  1  1
46           1  0  1 -1  1 -1  1
47           1  0 -1  1  1 -1  1
48           1  4  1  1  1  1  1
attr(,"assign")
[1] 0 1 2 3 4 5 6</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> truck<span class="sc">$</span>height</span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>y</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 7.78 8.15 7.50 7.59 7.94 7.69 7.56 7.56 7.50 7.88 7.50 7.63 7.32 7.56 7.18
[16] 7.81 7.78 8.18 7.56 7.56 8.00 8.09 7.62 7.81 7.25 7.88 7.56 7.75 7.44 7.69
[31] 7.18 7.50 7.81 7.88 7.50 7.75 7.88 8.06 7.44 7.69 7.12 7.44 7.50 7.56 7.44
[46] 7.62 7.25 7.59</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">try</span>(<span class="fu">solve</span>(<span class="fu">t</span>(X) <span class="sc">%*%</span> X) <span class="sc">%*%</span> <span class="fu">t</span>(X) <span class="sc">%*%</span> y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Error in solve.default(t(X) %*% X) : 
  Lapack routine dgesv: system is exactly singular: U[6,6] = 0</code></pre>
</div>
</div>
<p>The model cannot be estimated due to linear dependence among the predictors, which makes the design matrix rank-deficient.</p>
</section>
<section id="q7e" class="level4">
<h4 class="anchored" data-anchor-id="q7e">q7e</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a>qrx <span class="ot">&lt;-</span> <span class="fu">qr</span>(X)</span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(<span class="fu">qr.Q</span>(qrx))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 48  7</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">qr.Q</span>(qrx)) <span class="sc">%*%</span> y</span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a><span class="fu">backsolve</span>(<span class="fu">qr.R</span>(qrx), f)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>              [,1]
[1,]  7.636042e+00
[2,] -1.853252e+13
[3,]  1.853252e+13
[4,]  1.853252e+13
[5,]  1.853252e+13
[6,] -1.267479e-01
[7,]  1.853252e+13</code></pre>
</div>
</div>
</section>
<section id="q7f" class="level4">
<h4 class="anchored" data-anchor-id="q7f">q7f</h4>
<p>We will obtain the same results as <code>coef(lm_q7c)</code> running</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qr.coef</span>(qrx, truck<span class="sc">$</span>height)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)           A           B           C           D           E 
  7.6360417   0.0518750   0.0587500  -0.1400000  -0.0662500          NA 
          O 
 -0.1297917 </code></pre>
</div>
</div>
</section>
</section>
<section id="q8" class="level3">
<h3 class="anchored" data-anchor-id="q8">Q8</h3>
<section id="q8a" class="level4">
<h4 class="anchored" data-anchor-id="q8a">q8a</h4>
<p><span class="math display">\[
\begin{pmatrix}
1 &amp; 0\\
1 &amp; 0\\
1 &amp; 0\\
1 &amp; 1\\
1 &amp; 1\\
1 &amp; 1
\end{pmatrix}
\]</span></p>
</section>
<section id="q8b" class="level4">
<h4 class="anchored" data-anchor-id="q8b">q8b</h4>
<p>Given the matrix <span class="math inline">\(X\)</span> and vector <span class="math inline">\(y\)</span>:</p>
<p><span class="math display">\[
X = \begin{pmatrix}
1 &amp; 0 \\
1 &amp; 0 \\
1 &amp; 0 \\
1 &amp; 1 \\
1 &amp; 1 \\
1 &amp; 1
\end{pmatrix}, \quad
y = \begin{pmatrix}
y_1 \\ y_2 \\ y_3 \\ y_4 \\ y_5 \\ y_6
\end{pmatrix}
\]</span></p>
<p>We want to find the Least Squares estimator: <span class="math inline">\(\hat{\beta} = (X^T X)^{-1} X^T y\)</span>.</p>
<p><span class="math display">\[
X^T = \begin{pmatrix}
1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 \\
0 &amp; 0 &amp; 0 &amp; 1 &amp; 1 &amp; 1
\end{pmatrix}
\]</span></p>
<p><span class="math display">\[
X^T X = \begin{pmatrix}
1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 \\
0 &amp; 0 &amp; 0 &amp; 1 &amp; 1 &amp; 1
\end{pmatrix}
\begin{pmatrix}
1 &amp; 0 \\
1 &amp; 0 \\
1 &amp; 0 \\
1 &amp; 1 \\
1 &amp; 1 \\
1 &amp; 1
\end{pmatrix}
= \begin{pmatrix}
6 &amp; 3 \\
3 &amp; 3
\end{pmatrix}
\]</span></p>
<p><span class="math display">\[
(X^T X)^{-1} = \frac{1}{9} \begin{pmatrix}
3 &amp; -3 \\
-3 &amp; 6
\end{pmatrix} = \begin{pmatrix}
3/9 &amp; -3/9 \\
-3/9 &amp; 6/9
\end{pmatrix} = \begin{pmatrix}
1/3 &amp; -1/3 \\
-1/3 &amp; 2/3
\end{pmatrix}
\]</span></p>
<p><span class="math display">\[
X^T y = \begin{pmatrix}
1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 \\
0 &amp; 0 &amp; 0 &amp; 1 &amp; 1 &amp; 1
\end{pmatrix}
\begin{pmatrix}
y_1 \\ y_2 \\ y_3 \\ y_4 \\ y_5 \\ y_6
\end{pmatrix}
= \begin{pmatrix}
y_1 + y_2 + y_3 + y_4 + y_5 + y_6 \\
y_4 + y_5 + y_6
\end{pmatrix}
= \begin{pmatrix}
\sum_{i=1}^6 y_i \\
\sum_{i=4}^6 y_i
\end{pmatrix}
\]</span></p>
<p><span class="math display">\[
(X^T X)^{-1} (X^T y) =
\hat{\beta}
= \begin{pmatrix}
\hat{\beta}_0\\
\hat{\beta}_1
\end{pmatrix}
= \begin{pmatrix}
1/3 &amp; -1/3 \\
-1/3 &amp; 2/3
\end{pmatrix}
\begin{pmatrix}
y_1 + y_2 + y_3 + y_4 + y_5 + y_6\\
y_4 + y_5 + y_6
\end{pmatrix}
\]</span></p>
<p><span class="math display">\[
\begin{pmatrix}
\hat{\beta}_0\\
\hat{\beta}_1
\end{pmatrix}
= \begin{pmatrix}
\frac{y_1 + y_2 + y_3}{3}\\
\frac{y_4 + y_5 + y_6}{3} - \frac{y_1 + y_2 + y_3}{3}
\end{pmatrix}
= \begin{pmatrix}
\frac{1}{3} \sum_{i = 1}^3 y_i\\
\frac{1}{3} ( \sum_{i = 4}^6 y_i - \sum_{i = 1}^3 y_i )
\end{pmatrix}
\]</span></p>
<p><span class="math display">\[
\hat{\beta}_0 = \frac{y_1 + y_2 + y_3}{3} = \frac{1}{3} \sum_{i = 1}^3 y_i
\]</span></p>
<p>Notice that <span class="math inline">\(\hat{\beta}_0\)</span> is the mean of all the observations from the first group. (Think of it as the reference group in linear regression)</p>
<p><span class="math display">\[
\hat{\beta}_1 = \frac{1}{3} ( \sum_{i = 4}^6 y_i - \sum_{i = 1}^3 y_i )
\]</span></p>
<p>Notice that <span class="math inline">\(\hat{\beta}_1\)</span> is the difference between the means of both groups.</p>
</section>
<section id="q8c" class="level4">
<h4 class="anchored" data-anchor-id="q8c">q8c</h4>
<p><span class="math display">\[
\begin{pmatrix}
1 &amp; -1\\
1 &amp; -1\\
1 &amp; -1\\
1 &amp; 1\\
1 &amp; 1\\
1 &amp; 1
\end{pmatrix}
\]</span></p>
</section>
<section id="q8d" class="level4">
<h4 class="anchored" data-anchor-id="q8d">q8d</h4>
<p>Given the matrix <span class="math inline">\(X\)</span> and vector <span class="math inline">\(y\)</span> (where Group 1 is -1 and Group 2 is +1):</p>
<p><span class="math display">\[
X = \begin{pmatrix}
1 &amp; -1 \\
1 &amp; -1 \\
1 &amp; -1 \\
1 &amp; 1 \\
1 &amp; 1 \\
1 &amp; 1
\end{pmatrix}, \quad
y = \begin{pmatrix}
y_1 \\ y_2 \\ y_3 \\ y_4 \\ y_5 \\ y_6
\end{pmatrix}
\]</span></p>
<p>We want to find the Least Squares estimator: <span class="math inline">\(\hat{\beta} = (X^T X)^{-1} X^T y\)</span>.</p>
<p><span class="math display">\[
X^T = \begin{pmatrix}
1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 \\
-1 &amp; -1 &amp; -1 &amp; 1 &amp; 1 &amp; 1
\end{pmatrix}
\]</span></p>
<p><span class="math display">\[
X^T X = \begin{pmatrix}
1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 \\
-1 &amp; -1 &amp; -1 &amp; 1 &amp; 1 &amp; 1
\end{pmatrix}
\begin{pmatrix}
1 &amp; -1 \\
1 &amp; -1 \\
1 &amp; -1 \\
1 &amp; 1 \\
1 &amp; 1 \\
1 &amp; 1
\end{pmatrix}
= \begin{pmatrix}
6 &amp; 0 \\
0 &amp; 6
\end{pmatrix}
\]</span></p>
<p><span class="math display">\[
(X^T X)^{-1} = \begin{pmatrix}
1/6 &amp; 0 \\
0 &amp; 1/6
\end{pmatrix}
\]</span></p>
<p><span class="math display">\[
X^T y = \begin{pmatrix}
1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 &amp; 1 \\
-1 &amp; -1 &amp; -1 &amp; 1 &amp; 1 &amp; 1
\end{pmatrix}
\begin{pmatrix}
y_1 \\ y_2 \\ y_3 \\ y_4 \\ y_5 \\ y_6
\end{pmatrix}
= \begin{pmatrix}
y_1 + y_2 + y_3 + y_4 + y_5 + y_6 \\
-y_1 - y_2 - y_3 + y_4 + y_5 + y_6
\end{pmatrix}
= \begin{pmatrix}
\sum_{i=1}^6 y_i \\
\sum_{i=4}^6 y_i - \sum_{i=1}^3 y_i
\end{pmatrix}
\]</span></p>
<p><span class="math display">\[
(X^T X)^{-1} (X^T y) =
\hat{\beta}
= \begin{pmatrix}
\hat{\beta}_0\\
\hat{\beta}_1
\end{pmatrix}
= \begin{pmatrix}
1/6 &amp; 0 \\
0 &amp; 1/6
\end{pmatrix}
\begin{pmatrix}
\sum_{i=1}^6 y_i \\
\sum_{i=4}^6 y_i - \sum_{i=1}^3 y_i
\end{pmatrix}
\]</span></p>
<p><span class="math display">\[
\begin{pmatrix}
\hat{\beta}_0\\
\hat{\beta}_1
\end{pmatrix}
= \begin{pmatrix}
\frac{1}{6} \sum_{i = 1}^6 y_i \\
\frac{1}{6} ( \sum_{i = 4}^6 y_i - \sum_{i = 1}^3 y_i )
\end{pmatrix}
\]</span></p>
<p><span class="math display">\[
\hat{\beta}_0 = \frac{1}{6} \sum_{i = 1}^6 y_i
\]</span></p>
<p>Notice that <span class="math inline">\(\hat{\beta}_0\)</span> is now the grand mean (the average of all observations combined). All because -1 and 1 are centred around 0, and the intercept represents the centre of the data.</p>
<p><span class="math display">\[
\hat{\beta}_1 = \frac{1}{6} ( \sum_{i = 4}^6 y_i - \sum_{i = 1}^3 y_i )
\]</span></p>
<p>Notice that <span class="math inline">\(\hat{\beta}_1\)</span> is <strong>half the difference</strong> between the means of the two groups. (Since the difference in the x-axis “run” is now 2 units (from -1 to 1), the slope is halved compared to the 0/1 coding).</p>
<ul>
<li>The first coding computes the mean of one group (<span class="math inline">\(\hat{\beta}_0\)</span>) and then the difference in their means (<span class="math inline">\(\hat{\beta}_1\)</span>).</li>
<li>The second computes an overall mean (<span class="math inline">\(\hat{\beta}_0\)</span>) while the second parameter represents the difference from that overall mean (<span class="math inline">\(\hat{\beta}_1\)</span>).
<ul>
<li>The second coding is more symmetrical (but both result in the same fitted values and residuals).</li>
</ul></li>
</ul>
</section>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>